[build]
  command = "./build.sh"
  functions = "functions"
  publish = "public"

[build.environment]
  GO_IMPORT_PATH = "github.com/thisislink/learngo"
  GO111MODULE = "on"

  [[redirects]]
  from = "/*"
  to = "/.netlify/functions/gateway/:splat"
  status = 200